//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class acumuladore
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int SemanaAno { get; set; }
        public int CantidadPar { get; set; }
        public int AlmacenId { get; set; }
    
        public virtual almacene almacene { get; set; }
    }
}
