//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacene
    {
        public almacene()
        {
            this.acumuladores = new HashSet<acumuladore>();
        }
    
        public int Id { get; set; }
        public string NombreAlmacen { get; set; }
        public int CapacidadDiaria { get; set; }
        public int CapacidadSemanal { get; set; }
    
        public virtual ICollection<acumuladore> acumuladores { get; set; }
    }
}
