//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class almacene
    {
        public almacene()
        {
            this.acumuladores = new HashSet<acumuladore>();
        }
    
        public int Id { get; set; }
        public string NombreAlmacen { get; set; }
        public int CapacidadDiaria { get; set; }
        public int CapacidadSemanal { get; set; }
    
        public virtual ICollection<acumuladore> acumuladores { get; set; }
    }
}
