//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class andene
    {
        public andene()
        {
            this.rieles = new HashSet<riele>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Anden { get; set; }
    
        public virtual ICollection<riele> rieles { get; set; }
    }
}
