//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class andene
    {
        public andene()
        {
            this.rieles = new HashSet<riele>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Anden { get; set; }
    
        public virtual ICollection<riele> rieles { get; set; }
    }
}
