
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Ppgz.Repository
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetRole
{

    public AspNetRole()
    {

        this.AspNetUsers = new HashSet<AspNetUser>();

        this.perfiles = new HashSet<perfile>();

    }


    public string Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Tipo { get; set; }



    public virtual ICollection<AspNetUser> AspNetUsers { get; set; }

    public virtual ICollection<perfile> perfiles { get; set; }

}

}
