//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    public class audi
    {
        public int id { get; set; }
        public string NumeroEmpleado { get; set; }
        public string Nombreauditor { get; set; }
    }
}