//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cita
    {
        public cita()
        {
            this.asns = new HashSet<asn>();
            this.horariorieles = new HashSet<horarioriele>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaCita { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string Tienda { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
        public int ProveedorId { get; set; }
        public bool Borrado { get; set; }
        public Nullable<System.DateTime> FechaTx { get; set; }
        public string UsuarioIdTx { get; set; }
        public string OperacionTx { get; set; }
        public sbyte RielesOcupados { get; set; }
        public Nullable<int> EstatusCitaId { get; set; }
        public bool Penalizado { get; set; }
    
        public virtual ICollection<asn> asns { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual estatuscita estatuscita { get; set; }
        public virtual ICollection<horarioriele> horariorieles { get; set; }
    }
}
