//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        public cuenta()
        {
            this.cuentaproveedores = new HashSet<cuentaproveedore>();
            this.perfiles = new HashSet<perfile>();
            this.cuentasmensajes = new HashSet<cuentasmensaje>();
            this.aspnetusers = new HashSet<aspnetuser>();
        }
    
        public int Id { get; set; }
        public string CodigoProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Tipo { get; set; }
        public bool Activo { get; set; }
        public string ResponsableUsuarioId { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual ICollection<cuentaproveedore> cuentaproveedores { get; set; }
        public virtual ICollection<perfile> perfiles { get; set; }
        public virtual ICollection<cuentasmensaje> cuentasmensajes { get; set; }
        public virtual ICollection<aspnetuser> aspnetusers { get; set; }
    }
}
