//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasmensaje
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaVisualizacion { get; set; }
        public Nullable<int> MensajeId { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public string UsuarioId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual cuenta cuenta { get; set; }
        public virtual mensaje mensaje { get; set; }
    }
}
