//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        public cuenta()
        {
            this.usuarios_cuentas_xref = new HashSet<usuarios_cuentas_xref>();
        }
    
        public int id { get; set; }
        public string codigo_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int tipo_proveedor_id { get; set; }
        public Nullable<bool> activo { get; set; }
        public int reponsable_usuario_id { get; set; }
    
        public virtual ICollection<usuarios_cuentas_xref> usuarios_cuentas_xref { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
