//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentaproveedore
    {
        public string NumeroProveedor { get; set; }
        public string Nombre { get; set; }
        public string Ciudad { get; set; }
        public string Distrito { get; set; }
        public string VendedorNombre { get; set; }
        public string VendedorTelefono { get; set; }
        public string CompradorImpulsNombre { get; set; }
        public string CompradorImpulsTelefono { get; set; }
        public string CompradorImpulsEmail { get; set; }
        public int CuentaId { get; set; }
    
        public virtual cuenta cuenta { get; set; }
    }
}
