//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasmensaje
    {
        public int id { get; set; }
        public int CuentaId { get; set; }
        public int MensajeId { get; set; }
        public System.DateTime FechaVisualizacion { get; set; }
        public string UsuarioId { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual cuenta cuenta { get; set; }
        public virtual mensaje mensaje { get; set; }
    }
}
