//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleordencompra
    {
        public int Id { get; set; }
        public string Almacen { get; set; }
        public Nullable<sbyte> NumeroLineaOrden { get; set; }
        public string ItemCodigo { get; set; }
        public string ItemDescripcion { get; set; }
        public Nullable<decimal> ItemPrecio { get; set; }
        public string ItemSize { get; set; }
        public string ItemColor { get; set; }
        public string ItemEstilo { get; set; }
        public int ItemCantidad { get; set; }
        public int OrdenComprasId { get; set; }
    }
}
