//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucione
    {
        public int id { get; set; }
        public string Referencia { get; set; }
        public string Material { get; set; }
        public string Descripcion { get; set; }
        public string Cantidad { get; set; }
        public int Importe { get; set; }
    }
}
