//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucione
    {
        public int id { get; set; }
        public string Referencia { get; set; }
        public string Material { get; set; }
        public string Descripcion { get; set; }
        public string Cantidad { get; set; }
        public int Importe { get; set; }
    }
}
