//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    public class EnviarEtiquetas
    {
        public int id_eti { get; set; }
        public Nullable<int> cita { get; set; }
        public string carga { get; set; }
        public string recibo { get; set; }
        public string factura { get; set; }
        public string tienda { get; set; }
        public string caja { get; set; }
        public Nullable<int> pares { get; set; }
        public string estilo { get; set; }
        public string color { get; set; }
        public Nullable<int> Id_Proveedor { get; set; }
    }
}