//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    public class EnviarDatos
    {
        public  int id { get; set; }
        public string INTERFACE_RECORD_ID { get; set; }
        public string INTERFACE_LINK_ID { get; set; }
        public string INTERFACE_ACTION_CODE { get; set; }
        public string INTERFACE_CONDITION { get; set; }
        public string container_id { get; set; }
        public string container_type { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public string REASON_CODE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> TMP_ERP_ORDER_LINE_NUM { get; set; }
        public Nullable <int> Id_Proveedor { get; set; }
        public string Pedido { get; set; }
        public Nullable<int> CitaId { get; set; }
    }
}