//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class estatusfactoraje
    {
        public int idEstatusFactoraje { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Activo { get; set; }
    }
}
