//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class etiqueta
    {
        public int Id { get; set; }
        public string Archivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NumeroOrden { get; set; }
        public int ProveedorId { get; set; }
    
        public virtual proveedore proveedore { get; set; }
    }
}
