//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturasfactoraje
    {
        public int idFacturasFactoraje { get; set; }
        public string NumeroDocumento { get; set; }
        public string Monto { get; set; }
        public string uuid { get; set; }
        public int IdProveedor { get; set; }
        public int Porcentaje { get; set; }
        public string Referencia { get; set; }
        public int DiasPP { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int idSolicitudesFactoraje { get; set; }
        public int FacturaEstatus { get; set; }
        public double interes { get; set; }
    }
}
