//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class fakedataproveedor
    {
        public string NumeroDeProveedor { get; set; }
        public string ClavePais { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Nombre3 { get; set; }
        public string Nombre4 { get; set; }
        public string Ciudad { get; set; }
        public string Distrito { get; set; }
        public string POBox { get; set; }
        public string CodigoPostalDePOBox { get; set; }
        public string CodigoPostal { get; set; }
        public string Region { get; set; }
        public string Direccion { get; set; }
        public string Direccioncomplementaria { get; set; }
        public string Compania { get; set; }
        public string OrganizaciondeCompras { get; set; }
        public string MonedadelaOrdendeCompra { get; set; }
        public string Vendedor { get; set; }
        public string TelefonodelVendedor { get; set; }
        public string TerminosdePago { get; set; }
        public string ClavedeIncoterm { get; set; }
        public string DescripcinIncoterm { get; set; }
        public string GrupodeCompras { get; set; }
        public string NombredelCompradorImpuls { get; set; }
        public string TelefonodelCompradorImpuls { get; set; }
        public string Telefono2delCompradorImpuls { get; set; }
        public string ExtiensiondelCompradorImpuls { get; set; }
        public string EmaildelCompradorImpuls { get; set; }
    }
}
