//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class horarioriele
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Disponibilidad { get; set; }
        public int HorarioId { get; set; }
        public int AlmacenRielId { get; set; }
        public Nullable<int> CitaId { get; set; }
    
        public virtual cita cita { get; set; }
        public virtual horario horario { get; set; }
        public virtual riele riele { get; set; }
    }
}
