//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class horarioriele
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Disponibilidad { get; set; }
        public int HorarioId { get; set; }
        public int AlmacenRielId { get; set; }
        public Nullable<int> CitaId { get; set; }
        public string ComentarioBloqueo { get; set; }
        public string Citas { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
        public string CantidadPorCita { get; set; }
        public string TipoCita { get; set; }

        public virtual cita cita { get; set; }
        public virtual horario horario { get; set; }
        public virtual riele riele { get; set; }
    }
}
