//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public horario()
        {
            this.horariorieles = new HashSet<horarioriele>();
        }
    
        public int Id { get; set; }
        public int HoraDesde { get; set; }
        public int HoraHasta { get; set; }
    
        public virtual ICollection<horarioriele> horariorieles { get; set; }
    }
}
