//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class horario
    {
        public horario()
        {
            this.horariorieles = new HashSet<horarioriele>();
        }
    
        public int Id { get; set; }
        public int HoraDesde { get; set; }
        public int HoraHasta { get; set; }
    
        public virtual ICollection<horarioriele> horariorieles { get; set; }
    }
}
