//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class logfactoraje
    {
        public int idLogFactoraje { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Operacion { get; set; }
        public int IdObjeto { get; set; }
        public int TipoObjeto { get; set; }
        public string Descripcion { get; set; }
        public string Usuario { get; set; }
    }
}
