//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    public class MensajeResultado
    {
        public int IdRev { get; set; }
        public string MsjError { get; set; }
        public string DatoConDetalle { get; set; }
        public int IdProveedor { get; set; }
        public string Cuenta { get; set; }
    }
}