//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        public mensaje()
        {
            this.mensajes_usuarios_xref = new HashSet<mensajes_usuarios_xref>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public string archivo { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
    
        public virtual ICollection<mensajes_usuarios_xref> mensajes_usuarios_xref { get; set; }
    }
}
