//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class niveleseervicio
    {
        public int Id { get; set; }
        public int ProveedorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal UltimoMes { get; set; }
        public decimal TemporadaActual { get; set; }
        public decimal AcumuladoAnual { get; set; }
        public decimal PedidoAtrasado { get; set; }
        public decimal PedidoEnTiempo { get; set; }
        public decimal PedidoTotal { get; set; }
    
        public virtual proveedore proveedore { get; set; }
    }
}
