//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class niveleseervicio
    {
        public int Id { get; set; }
        public int ProveedorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal UltimoMes { get; set; }
        public decimal TemporadaActual { get; set; }
        public decimal AcumuladoAnual { get; set; }
        public decimal PedidoAtrasado { get; set; }
        public decimal PedidoEnTiempo { get; set; }
        public decimal PedidoTotal { get; set; }
    
        public virtual proveedore proveedore { get; set; }
    }
}
