//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordencompradetalle
    {
        public int Id { get; set; }
        public string NumeroDocumento { get; set; }
        public string Ebelp { get; set; }
        public string DescripcionMaterial { get; set; }
        public string NumeroMaterial { get; set; }
        public string Centro { get; set; }
        public string Almacen { get; set; }
        public string GrupoArticulos { get; set; }
        public string CantidadPedido { get; set; }
        public string UnidadMedidaPedido { get; set; }
        public string UnidadMedidaPrecio { get; set; }
        public Nullable<int> ConversionUmpruMP { get; set; }
        public Nullable<int> ConversionUmUmBase { get; set; }
        public Nullable<int> DenominadorUmUmBase { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public Nullable<int> CantidadBase { get; set; }
        public Nullable<decimal> ValorNeto { get; set; }
        public Nullable<decimal> ValorBruto { get; set; }
        public Nullable<decimal> CantidadUnidadMedida { get; set; }
        public Nullable<int> SapOrdenCompraId { get; set; }
        public System.DateTime FechaCargaPortal { get; set; }
        public decimal CantidadComprometida { get; set; }
    
        public virtual ordencompra ordencompra { get; set; }
    }
}
