//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago
    {
        public int id { get; set; }
        public string RFC { get; set; }
        public string RazonSocial { get; set; }
        public string NumeroCompensacion { get; set; }
        public string Referencia { get; set; }
        public string FechaDePago { get; set; }
        public string FechaBase { get; set; }
        public string Importe { get; set; }
        public string ML { get; set; }
        public string TipoMovimiento { get; set; }
    }
}
