//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acumuladore> acumuladores { get; set; }
        public virtual DbSet<almacene> almacenes { get; set; }
        public virtual DbSet<andene> andenes { get; set; }
        public virtual DbSet<asn> asns { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<configuracione> configuraciones { get; set; }
        public virtual DbSet<cr> crs { get; set; }
        public virtual DbSet<cuentaproveedore> cuentaproveedores { get; set; }
        public virtual DbSet<cuenta> cuentas { get; set; }
        public virtual DbSet<cuentasmensaje> cuentasmensajes { get; set; }
        public virtual DbSet<estatuscita> estatuscitas { get; set; }
        public virtual DbSet<etiqueta> etiquetas { get; set; }
        public virtual DbSet<horarioriele> horariorieles { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<impuls_logs> impuls_logs { get; set; }
        public virtual DbSet<mensaje> mensajes { get; set; }
        public virtual DbSet<niveleseervicio> niveleseervicios { get; set; }
        public virtual DbSet<ordencompra> ordencompras { get; set; }
        public virtual DbSet<ordencompradetalle> ordencompradetalles { get; set; }
        public virtual DbSet<perfile> perfiles { get; set; }
        public virtual DbSet<proveedore> proveedores { get; set; }
        public virtual DbSet<riele> rieles { get; set; }
        public virtual DbSet<tipocuenta> tipocuentas { get; set; }
        public virtual DbSet<tipousuario> tipousuarios { get; set; }
        public virtual DbSet<devolucione> devoluciones { get; set; }
        public virtual DbSet<pago> pagos { get; set; }
        public virtual DbSet<vwdashboard> vwdashboards { get; set; }
        public virtual DbSet<vwmensaje> vwmensajes { get; set; }
    }
}
