//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedorfactoraje
    {
        public int idProveedore { get; set; }
        public int Porcentaje { get; set; }
        public int DiaDePago { get; set; }
        public string Correo { get; set; }
    }
}
