//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedore
    {
        public int Id { get; set; }
        public string CodigoProveedor { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> CuentaId { get; set; }
        public bool Borrado { get; set; }
        public Nullable<System.DateTime> FechaTx { get; set; }
        public string UsuarioIdTx { get; set; }
        public string OperacionTx { get; set; }
        public string NombreProveedor { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string CodigoPostal { get; set; }
        public string direccion1 { get; set; }
        public string direccion2 { get; set; }
        public string direccion3 { get; set; }
        public string email { get; set; }
        public string Rfc { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual cuenta cuenta { get; set; }
    }
}
