//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Ppgz.Repository
{
    public class reenvio
    {
        public int Id { get; set; }
        public Nullable<int> IdCita { get; set; }
        public Nullable<int> Pares { get; set; }
        public System.DateTime FechaCita { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string Almacen { get; set; }
    }
}