//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    public class RevisarPedidos
    {
        public int id { get; set; }
        public string Pedido { get; set; }
        public string Material { get; set; }
        public int Cantidad { get; set; }
        public int Id_Proveedor { get; set; }
        public string Numero_linea { get; set; }
        public string Cuenta { get; set; }
        
    }
}