//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Ppgz.Repository
{
    public class RevisarDatos
    {
        public int id { get; set; }
        public string Carga { get; set; }
        public string Caja { get; set; }
        public string Factura { get; set; }
        public string Pedido { get; set; }
        public string Tienda { get; set; }
        public string EAN { get; set; }
        public int Pares { get; set; }
        public string Material { get; set; }
        public int Id_Proveedor { get; set; }
        public int Edo_Rev { get; set; }
        public int CitaId { get; set; }
        public string Estilo { get; set; }
        public string Color { get; set; }
        public string Cuenta { get; set; }
    }
}