//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class riele
    {
        public riele()
        {
            this.horariorieles = new HashSet<horarioriele>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Riel { get; set; }
        public int AndenId { get; set; }
    
        public virtual andene andene { get; set; }
        public virtual ICollection<horarioriele> horariorieles { get; set; }
    }
}
