//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudesfactoraje
    {
        public int idSolicitudesFactoraje { get; set; }
        public int IdProveedor { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int EstatusFactoraje { get; set; }
        public string Comentario { get; set; }
        public int DiasPP { get; set; }
        public int NDocumentos { get; set; }
        public string xml { get; set; }
        public string pdf { get; set; }
        public double MontoOriginal { get; set; }
        public double MontoAFacturar { get; set; }
        public double Descuentos { get; set; }
        public double DescuentoPP { get; set; }
        public Nullable<int> NumeroGenerado { get; set; }
        public string EstatusOperacionSAP { get; set; }
        public string Sociedad { get; set; }
    }
}
