//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_cuentas_xref
    {
        public int usuario_id { get; set; }
        public int cuenta_id { get; set; }
        public string usuarios_cuentas_xrefcol { get; set; }
    
        public virtual cuenta cuenta { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
