//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.cuentas = new HashSet<cuenta>();
            this.usuarios_cuentas_xref = new HashSet<usuarios_cuentas_xref>();
        }
    
        public int Id { get; set; }
        public string userName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<int> tipo_usuario_id { get; set; }
        public Nullable<int> perfil_id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string cargo { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> primer_acceso { get; set; }
        public Nullable<System.DateTime> ultimo_acceso { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<System.DateTime> fecha_desactivado { get; set; }
    
        public virtual ICollection<cuenta> cuentas { get; set; }
        public virtual tipos_usuario tipos_usuario { get; set; }
        public virtual ICollection<usuarios_cuentas_xref> usuarios_cuentas_xref { get; set; }
    }
}
