//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwdashboard
    {
        public int horarioRielId { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Disponibilidad { get; set; }
        public int HorarioId { get; set; }
        public int AlmacenRielId { get; set; }
        public Nullable<int> CitaId { get; set; }
        public string Riel { get; set; }
        public int AndenId { get; set; }
        public string Anden { get; set; }
        public string Desde { get; set; }
        public string Hasta { get; set; }
        public Nullable<int> ProveedorId { get; set; }
    }
}
