//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwdashboard
    {
        public int horarioRielId { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Disponibilidad { get; set; }
        public int HorarioId { get; set; }
        public int AlmacenRielId { get; set; }
        public Nullable<int> CitaId { get; set; }
        public string Riel { get; set; }
        public int AndenId { get; set; }
        public string Anden { get; set; }
        public string Desde { get; set; }
        public string Hasta { get; set; }
        public Nullable<int> ProveedorId { get; set; }
    }
}
