//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServiceWCF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
	""fechaCita"":""21/04/2017"",
	""tienda"":""T001"",
	""cantidadTotal"":10,
	""proveedorId"": 33,
	""usuarioId"":""15e814e8-0967-46e1-9a9d-fdfb7a1f2d4b"",
	""asnItems"":[{
		""numeroPosicion"":""0015"",
		""ordenNumeroDocumento"":""0001"",
		""numeroMaterial"":""MAT01"",
		""nombreMaterial"":""Zapatos"",
		""cantidad"": 5
	}]
}")]
        public string TestJSON {
            get {
                return ((string)(this["TestJSON"]));
            }
        }
    }
}
