
/* Configuraciones Generales */
-- 1 Configuración de citas 
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.working-day.enabled' AS Clave, '2,3,4,5,6' AS Valor, 1 AS Habilitado, 'Indica los dias de la semana, donde 1=Domingo, 2=Lunes,...7=Sabado, donde se pueden hacer las recepciones de mercancias o entregas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.working-day.enabled');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.special-day.provider' AS Clave, '4' AS Valor, 1 AS Habilitado, 'Indica el dia de entrega para los proveedores pronto pago' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.special-day.provider');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.max-pairs.per-day' AS Clave, '27000' AS Valor, 1 AS Habilitado, 'Indica la cantidad maxima de pares por dia permitida' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.max-pairs.per-day');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.max-pairs.per-week' AS Clave, '90000' AS Valor, 1 AS Habilitado, 'Indica la cantidad maxima de pares por semana permitida' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.max-pairs.per-week');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.crossdock-max-pairs.per-day' AS Clave, '27000' AS Valor, 1 AS Habilitado, 'Indica la cantidad maxima de pares por dia permitida para crossdock' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.crossdock-max-pairs.per-day');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.platform-rail.max-pair.hour' AS Clave, '700' AS Valor, 1 AS Habilitado, 'Indica la cantidad maxima de pares por hora por riel permitida' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.platform-rail.max-pair.hour');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.platform-rail.max-pair.30min' AS Clave, '250' AS Valor, 1 AS Habilitado, 'Indica la cantidad maxima de pares cada media hora por riel permitida' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.platform-rail.max-pair.30min');
	/*INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.platform-rail.max-pair-hour.tolerance' AS Clave, '0.16' AS Valor, 1 AS Habilitado, 'Indica la tolerancia en márgenes de pares por hora' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.platform-rail.max-pair-hour.tolerance');*/
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.warehouses' AS Clave, 'CD01,CD02,CD03,CD04,CD05,CD06' AS Valor, 1 AS Habilitado, 'Codigos SAP de todos los almacenes' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.warehouses');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.limited-warehouses-per-day' AS Clave, 'CD01,CD06' AS Valor, 1 AS Habilitado, 'Codigos SAP de los almacenes que tienen cantidades limitadas por dia' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.limited-warehouses-per-day');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.limited-warehouses-per-week' AS Clave, 'CD01,CD06' AS Valor, 1 AS Habilitado, 'Codigos SAP de los almacenes que tienen cantidades limitadas por semana' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.limited-warehouses-per-week');	
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'warehouse.deadline-hour-next-day' AS Clave, '17' AS Valor, 1 AS Habilitado, 'Inidca la hora tope para agendar las citas del siguiente día. Debe ser en formato entero 24 horas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'warehouse.deadline-hour-next-day');
-- 2 Configuración del url del portal
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'site.url' AS Clave, 'http://ppgz.com' AS Valor, 1 AS Habilitado, 'Indica la dirección del portal' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'site.url');
-- 3 Configuración del servidor de correos
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'mail.main.address' AS Clave, 'impuls.ppgz@gmail.com' AS Valor, 1 AS Habilitado, 'Indica  la dirección del correo emisor' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'mail.main.address');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'mail.main.password' AS Clave, 'Venezuela2017' AS Valor, 1 AS Habilitado, 'Indica la contraseña del correo emisor' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'mail.main.password');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'mail.main.smtp.host' AS Clave, 'smtp.gmail.com' AS Valor, 1 AS Habilitado, 'Indica el host del servidor smtp del correo emisor' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'mail.main.smtp.host');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'mail.main.smtp.port' AS Clave, '587' AS Valor, 1 AS Habilitado, 'Indica el puerto del servidor smtp del correo emisor' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'mail.main.smtp.port');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'mail.main.smtp.enablessl' AS Clave, '1' AS Valor, 1 AS Habilitado, 'Indica si la conexión del servidor smtp require ssl' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'mail.main.smtp.enablessl');
-- 4 Configuración del Servidor RFC de BW
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.name' AS Clave, 'QIM' AS Valor, 1 AS Habilitado, 'Indica el Nombre del Ambiente del Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.name');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.appserverhost' AS Clave, '172.18.3.16' AS Valor, 1 AS Habilitado, 'Indica la dirección IP del Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.appserverhost');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.user' AS Clave, 'USRPORTAL' AS Valor, 1 AS Habilitado, 'Indica el Usuario del Del Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.user');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.password' AS Clave, 'wspportalp' AS Valor, 1 AS Habilitado, 'Indica la contraseña del Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.password');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.client' AS Clave, '600' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.client');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.systemnumber' AS Clave, '50' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.systemnumber');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.language' AS Clave, 'ES' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.language');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.poolsize' AS Clave, '5' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.poolsize');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.peakconnectionslimit' AS Clave, '35' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.peakconnectionslimit');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.bw.idletimeout' AS Clave, '500' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC para BW' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.bw.idletimeout');
-- 5 Configuración del Servidor RFC General
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.name' AS Clave, 'QIM' AS Valor, 1 AS Habilitado, 'Indica el Nombre del Ambiente del Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.name');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.appserverhost' AS Clave, '172.18.3.21' AS Valor, 1 AS Habilitado, 'Indica la dirección IP del Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.appserverhost');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.user' AS Clave, 'WSPRR' AS Valor, 1 AS Habilitado, 'Indica el Usuario del Del Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.user');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.password' AS Clave, 'wsp2017' AS Valor, 1 AS Habilitado, 'Indica la contraseña del Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.password');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.client' AS Clave, '300' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.client');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.systemnumber' AS Clave, '22' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.systemnumber');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.language' AS Clave, 'ES' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.language');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.poolsize' AS Clave, '5' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.poolsize');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.peakconnectionslimit' AS Clave, '35' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.peakconnectionslimit');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.main.idletimeout' AS Clave, '500' AS Valor, 1 AS Habilitado, 'Campo requerido para la conexión al Servidor RFC General' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.main.idletimeout');
-- 6 Configuración de Procesador de Archivos Batch y Otros Archivos

	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'batchfile.daemon' AS Clave, 'C:\\Ppgz\\BatchFileProcessor\\Ppgz.BatchFileProcessor.exe' AS Valor, 1 AS Habilitado, 'Indica la ruta de la aplicación que procesará los arhivos batch.' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'batchfile.daemon');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'batchfile.wrongfilespath' AS Clave, 'C:\\Ppgz\\WrongFiles' AS Valor, 1 AS Habilitado, 'Indica la ruta del directorio para los archivos incorrectos. Estos serán los archivos que no pudieron ser procesados por el sistema.' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'batchfile.wrongfilespath');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'batchfile.crinboxpath' AS Clave, 'C:\\Ppgz\\Cr\\Inbox' AS Valor, 1 AS Habilitado, 'Indica la ruta del directorio de entrada de los archivos CRs' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'batchfile.crinboxpath');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'batchfile.crpath' AS Clave, 'C:\\Ppgz\\Cr\\Processed' AS Valor, 1 AS Habilitado, 'Indica la ruta del directorio de archivos CRs procesados' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'batchfile.crpath');
	/*INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'batchfile.crfilter' AS Clave, 'cr_*.pdf' AS Valor, 1 AS Habilitado, '' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'batchfile.crfilter');*/
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'facturas.rootdirectory' AS Clave, 'c:\\Ppgz\\Facturas' AS Valor, 1 AS Habilitado, 'Indica la ruta del directorio de facturas procesadas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'facturas.rootdirectory');
	
-- 7 Configuracion de parámetros del negocio para los RFC	
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.common.function.param.bukrs.mercaderia' AS Clave, '1001' AS Valor, 1 AS Habilitado, 'Parámetro de la Sociedad de Compras que será enviado para todos los proveedores registrados como Mercaderías' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.common.function.param.bukrs.mercaderia');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.common.function.param.bukrs.servicio' AS Clave, '1000' AS Valor, 1 AS Habilitado, 'Parámetro de la Sociedad de Compras que será enviado para todos los proveedores registrados como Servicio' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.common.function.param.bukrs.servicio');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.common.function.param.ekorg.mercaderia' AS Clave, 'OC01' AS Valor, 1 AS Habilitado, 'Parámetro de la Organización de Compras que será enviado para todos los proveedores registrados como Mercaderías' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.common.function.param.ekorg.mercaderia');
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'rfc.common.function.param.ekorg.servicio' AS Clave, 'OC02' AS Valor, 1 AS Habilitado, 'Parámetro de la Organización de Compras que será enviado para todos los proveedores registrados como Servicio' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'rfc.common.function.param.ekorg.servicio');

	/*INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'wfc.url.cita.add' AS Clave, 'http://localhost:14766/CitationControlService.svc/rest/AddCitation' AS Valor, 1 AS Habilitado, 'Url para el servicio que persiste las citas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'wfc.url.cita.add');*/

-- 8 Configuracion de parámetros para el validador de facturas			
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'cfdi.token' AS Clave, 'tokSY9Db304Kx' AS Valor, 1 AS Habilitado, 'Parámetro requerido para el servicio web de validación de facturas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'cfdi.token');      
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'cfdi.password' AS Clave, 'pswNfFPAaQhJ2' AS Valor, 1 AS Habilitado, 'Parámetro requerido para el servicio web de validación de facturas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'cfdi.password');      
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'cfdi.user' AS Clave, 'usraLYhIjXOCJ' AS Valor, 1 AS Habilitado, 'Parámetro requerido para el servicio web de validación de facturas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'cfdi.user');       
	INSERT INTO configuraciones (Clave, Valor, Habilitado, Descripcion) SELECT 'cfdi.cuenta' AS Clave, 'ctaduPw4Xeh0w' AS Valor, 1 AS Habilitado, 'Parámetro requerido para el servicio web de validación de facturas' AS Descripcion FROM dual WHERE NOT EXISTS(SELECT * FROM configuraciones WHERE Clave = 'cfdi.cuenta');        
/* Fin > Configuraciones Generales */
   
