//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        public cuenta()
        {
            this.aspnetusers = new HashSet<aspnetuser>();
        }
    
        public int id { get; set; }
        public string codigo_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int tipo_proveedor_id { get; set; }
        public Nullable<bool> activo { get; set; }
        public string reponsable_usuario_id { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual ICollection<aspnetuser> aspnetusers { get; set; }
    }
}
