//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_mensajes
    {
        public int id { get; set; }
        public int mensaje_id { get; set; }
        public string usuario_id { get; set; }
        public Nullable<System.DateTime> fecha_visualizacion { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual mensaje mensaje { get; set; }
    }
}
