//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Services {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonMensajesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMensajesResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ppgz.Services.CommonMensajesResource", typeof(CommonMensajesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de proveedor incorrecto.
        /// </summary>
        internal static string ERRO_Sap_ProveedorCodigo {
            get {
                return ResourceManager.GetString("ERRO_Sap_ProveedorCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cr incorrecto.
        /// </summary>
        internal static string ERROR_Cr_Id {
            get {
                return ResourceManager.GetString("ERROR_Cr_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta incorrecta.
        /// </summary>
        internal static string ERROR_Cuenta_Id {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una cuenta con ese nombre de proveedor.
        /// </summary>
        internal static string ERROR_Cuenta_NombreProveedorDuplicado {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_NombreProveedorDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de cuenta incorrecto.
        /// </summary>
        internal static string ERROR_Cuenta_Tipo {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta ya tiene un usuario maestro..
        /// </summary>
        internal static string ERROR_Cuenta_YaTieneUsuarioMaestro {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_YaTieneUsuarioMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta incorrecta.
        /// </summary>
        internal static string ERROR_CuentaManager_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede elminar el superadmin del sistema.
        /// </summary>
        internal static string ERROR_EliminarSuperAdmin {
            get {
                return ResourceManager.GetString("ERROR_EliminarSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar el registro..
        /// </summary>
        internal static string ERROR_General {
            get {
                return ResourceManager.GetString("ERROR_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su cuenta ha sido bloqueada por {0} minutos debido a {1} intentos fallidos..
        /// </summary>
        internal static string ERROR_Identity_UsuarioBloqueadoTemporalmente {
            get {
                return ResourceManager.GetString("ERROR_Identity_UsuarioBloqueadoTemporalmente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o Password incorrecto.
        /// </summary>
        internal static string ERROR_Identity_UsuarioPassword {
            get {
                return ResourceManager.GetString("ERROR_Identity_UsuarioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre o apellido incorrecto.
        /// </summary>
        internal static string Error_NombreApellido {
            get {
                return ResourceManager.GetString("Error_NombreApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya fue utilizado. Por favor intente con otro..
        /// </summary>
        internal static string ERROR_NombreUsuarioExistente {
            get {
                return ResourceManager.GetString("ERROR_NombreUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encuentra una orden de compra activa con ese número de documento para el proveedor.
        /// </summary>
        internal static string ERROR_OrdenCompraActiva_NumeroDocumento {
            get {
                return ResourceManager.GetString("ERROR_OrdenCompraActiva_NumeroDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesos incorrectos.
        /// </summary>
        internal static string ERROR_Perfil_AccesosIncorrectos {
            get {
                return ResourceManager.GetString("ERROR_Perfil_AccesosIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe agregar por lo menos 1 acceso al perfil.
        /// </summary>
        internal static string ERROR_Perfil_AccesosRequeridos {
            get {
                return ResourceManager.GetString("ERROR_Perfil_AccesosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar un perfil con usuarios.
        /// </summary>
        internal static string ERROR_Perfil_EliminarConUsarios {
            get {
                return ResourceManager.GetString("ERROR_Perfil_EliminarConUsarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar un perfil maestro.
        /// </summary>
        internal static string ERROR_Perfil_EliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_Perfil_EliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil incorrecto.
        /// </summary>
        internal static string ERROR_Perfil_Id {
            get {
                return ResourceManager.GetString("ERROR_Perfil_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del perfil ya fue utilizado.
        /// </summary>
        internal static string ERROR_Perfil_NombreExistente {
            get {
                return ResourceManager.GetString("ERROR_Perfil_NombreExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de perfil incorrecto.
        /// </summary>
        internal static string ERROR_Perfil_Tipo {
            get {
                return ResourceManager.GetString("ERROR_Perfil_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe agregar por lo menos 1 acceso al perfil.
        /// </summary>
        internal static string ERROR_PerfilProveedor_AccesosRequeridos {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_AccesosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede editar o eliminar el perfil Maestro.
        /// </summary>
        internal static string ERROR_PerfilProveedor_EditarEliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_EditarEliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar un perfil que tiene usuarios asociados.
        /// </summary>
        internal static string ERROR_PerfilProveedor_EliminarConUsuarios {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_EliminarConUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar el Perfil Maestro.
        /// </summary>
        internal static string ERROR_PerfilProveedor_EliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_EliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre para el perfil ya fue utilizado.
        /// </summary>
        internal static string ERROR_PerfilProveedor_NombreExistente {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_NombreExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pefil incorrecto.
        /// </summary>
        internal static string ERROR_PerfilProveedor_PefilIdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_PefilIdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor Incorrecto.
        /// </summary>
        internal static string ERROR_Proveedor_Id {
            get {
                return ResourceManager.GetString("ERROR_Proveedor_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El provedor ya esta asociado a una cuenta.
        /// </summary>
        internal static string ERROR_ProveedorSapYaAsociado {
            get {
                return ResourceManager.GetString("ERROR_ProveedorSapYaAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permiso incorrecto.
        /// </summary>
        internal static string ERROR_Role_Id {
            get {
                return ResourceManager.GetString("ERROR_Role_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el número telefónico.
        /// </summary>
        internal static string Error_Telefono {
            get {
                return ResourceManager.GetString("Error_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede cambiar el prefier de usuario maestro proveedor.
        /// </summary>
        internal static string ERROR_UsarioMaestroProveedor_CambiarPerfil {
            get {
                return ResourceManager.GetString("ERROR_UsarioMaestroProveedor_CambiarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario incorrecto.
        /// </summary>
        internal static string ERROR_Usuario_Id {
            get {
                return ResourceManager.GetString("ERROR_Usuario_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de usuario incorrecto.
        /// </summary>
        internal static string ERROR_Usuario_Tipo {
            get {
                return ResourceManager.GetString("ERROR_Usuario_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar el Usuario Maestro.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_EliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_EliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puede eliminar su propio usuario.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_EliminarPropioUsuario {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_EliminarPropioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Incorrecto.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario registrado con este login.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_LoginExistente {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de usuario incorrecto.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_TipoIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_TipoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil actualizado correctamente, los usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_PerfilProveedor_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilProveedor_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil creado correctamente.
        /// </summary>
        internal static string INFO_PerfilProveedor_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilProveedor_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil eliminado correctamente.
        /// </summary>
        internal static string INFO_PerfilProveedor_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilProveedor_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor actualizado correctamente.
        /// </summary>
        internal static string INFO_Proveedor_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Proveedor_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor creado correctamente.
        /// </summary>
        internal static string INFO_Proveedor_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Proveedor_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor eliminado correctamente.
        /// </summary>
        internal static string INFO_Proveedor_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_Proveedor_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario actualizado correctamente, el usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_UsuarioProveedor_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioProveedor_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario creado correctamente.
        /// </summary>
        internal static string INFO_UsuarioProveedor_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioProveedor_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario eliminado correctamente.
        /// </summary>
        internal static string INFO_UsuarioProveedor_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioProveedor_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo guardar. Intente nuevamente si el problema persiste contacte los adminsitradores del sistema..
        /// </summary>
        internal static string RegistroGeneral {
            get {
                return ResourceManager.GetString("RegistroGeneral", resourceCulture);
            }
        }
    }
}
