//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonMensajesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMensajesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ppgz.Services.CommonMensajesResource", typeof(CommonMensajesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta incorrecta.
        /// </summary>
        internal static string ERROR_Cuenta_Id {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una cuenta con ese nombre de proveedor.
        /// </summary>
        internal static string ERROR_Cuenta_NombreProveedorDuplicado {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_NombreProveedorDuplicado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de cuenta incorrecto.
        /// </summary>
        internal static string ERROR_Cuenta_Tipo {
            get {
                return ResourceManager.GetString("ERROR_Cuenta_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta incorrecta.
        /// </summary>
        internal static string ERROR_CuentaManager_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al procesar el registro..
        /// </summary>
        internal static string ERROR_General {
            get {
                return ResourceManager.GetString("ERROR_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su cuenta ha sido bloqueada por {0} minutos debido a {1} intentos fallidos..
        /// </summary>
        internal static string ERROR_Identity_UsuarioBloqueadoTemporalmente {
            get {
                return ResourceManager.GetString("ERROR_Identity_UsuarioBloqueadoTemporalmente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario o Password incorrecto.
        /// </summary>
        internal static string ERROR_Identity_UsuarioPassword {
            get {
                return ResourceManager.GetString("ERROR_Identity_UsuarioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de usuario ya fue utilizado. Por favor intente con otro..
        /// </summary>
        internal static string ERROR_NombreUsuarioExistente {
            get {
                return ResourceManager.GetString("ERROR_NombreUsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar por lo menos 1 acceso al perfil.
        /// </summary>
        internal static string ERROR_Perfil_AccesosRequeridos {
            get {
                return ResourceManager.GetString("ERROR_Perfil_AccesosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del perfil ya fue utilizado.
        /// </summary>
        internal static string ERROR_Perfil_NombreExistente {
            get {
                return ResourceManager.GetString("ERROR_Perfil_NombreExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de perfil incorrecto.
        /// </summary>
        internal static string ERROR_Perfil_Tipo {
            get {
                return ResourceManager.GetString("ERROR_Perfil_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar por lo menos 1 acceso al perfil.
        /// </summary>
        internal static string ERROR_PerfilProveedor_AccesosRequeridos {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_AccesosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede editar o eliminar el perfil Maestro.
        /// </summary>
        internal static string ERROR_PerfilProveedor_EditarEliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_EditarEliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar un perfil que tiene usuarios asociados.
        /// </summary>
        internal static string ERROR_PerfilProveedor_EliminarConUsuarios {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_EliminarConUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar el Perfil Maestro.
        /// </summary>
        internal static string ERROR_PerfilProveedor_EliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_EliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre para el perfil ya fue utilizado.
        /// </summary>
        internal static string ERROR_PerfilProveedor_NombreExistente {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_NombreExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pefil incorrecto.
        /// </summary>
        internal static string ERROR_PerfilProveedor_PefilIdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_PerfilProveedor_PefilIdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permiso incorrecto.
        /// </summary>
        internal static string ERROR_Role_Id {
            get {
                return ResourceManager.GetString("ERROR_Role_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario incorrecto.
        /// </summary>
        internal static string ERROR_Usuario_Id {
            get {
                return ResourceManager.GetString("ERROR_Usuario_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuario incorrecto.
        /// </summary>
        internal static string ERROR_Usuario_Tipo {
            get {
                return ResourceManager.GetString("ERROR_Usuario_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar el Usuario Maestro.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_EliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_EliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar su propio usuario.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_EliminarPropioUsuario {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_EliminarPropioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Incorrecto.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con este login.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_LoginExistente {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de usuario incorrecto.
        /// </summary>
        internal static string ERROR_UsuarioProveedor_TipoIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_UsuarioProveedor_TipoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil actualizado correctamente, los usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_PerfilProveedor_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilProveedor_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil creado correctamente.
        /// </summary>
        internal static string INFO_PerfilProveedor_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilProveedor_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil eliminado correctamente.
        /// </summary>
        internal static string INFO_PerfilProveedor_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilProveedor_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actualizad correctamente, el usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_UsuarioProveedor_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioProveedor_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado correctamente.
        /// </summary>
        internal static string INFO_UsuarioProveedor_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioProveedor_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario eliminado correctamente.
        /// </summary>
        internal static string INFO_UsuarioProveedor_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioProveedor_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo guardar. Intente nuevamente si el problema persiste contacte los adminsitradores del sistema..
        /// </summary>
        internal static string RegistroGeneral {
            get {
                return ResourceManager.GetString("RegistroGeneral", resourceCulture);
            }
        }
    }
}
