//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ppgz.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensajesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ppgz.Services.MensajesResource", typeof(MensajesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya exíste un usuario con ese login.
        /// </summary>
        internal static string ERROR_CuentaManager_Crear_LoginExistente {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_Crear_LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya exíste una cuenta maestra de proveedor registrada con este nombre.
        /// </summary>
        internal static string ERROR_CuentaManager_Crear_NombreProveedorExistente {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_Crear_NombreProveedorExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de proveedor Incorrecto.
        /// </summary>
        internal static string ERROR_CuentaManager_GetTipoByString {
            get {
                return ResourceManager.GetString("ERROR_CuentaManager_GetTipoByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR_General.
        /// </summary>
        internal static string ERROR_General {
            get {
                return ResourceManager.GetString("ERROR_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del mensaje es incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_ContenidoIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_ContenidoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de caducidad debe ser superior a la fecha de publicación.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_Crear_FechaCadMayor {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_Crear_FechaCadMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de publicación incorrecta, debe ser mayor o igual a la fecha actual.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_FechaPublicacion {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_FechaPublicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviado a Incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_GetEnviadoAByString {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_GetEnviadoAByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje no existe.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_MensajeNoExiste {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_MensajeNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El archivo de PDF es incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_PdfIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_PdfIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser un archivo PDF válido.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_PdfInvalido {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_PdfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titulo incorrecto.
        /// </summary>
        internal static string ERROR_MensajesInstitucionales_TituloIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_MensajesInstitucionales_TituloIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accesos incorrectos.
        /// </summary>
        internal static string ERROR_Perfil_AccesosIncorrectos {
            get {
                return ResourceManager.GetString("ERROR_Perfil_AccesosIncorrectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe agregar por lo menos 1 acceso al perfil.
        /// </summary>
        internal static string ERROR_PerfilNazan_AccesosRequeridos {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_AccesosRequeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede editar o eliminar el perfil Maestro.
        /// </summary>
        internal static string ERROR_PerfilNazan_EditarEliminarMaestro {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EditarEliminarMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar un perfil que tiene usuarios asociados.
        /// </summary>
        internal static string ERROR_PerfilNazan_EliminarConUsuarios {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EliminarConUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar su propio usuario..
        /// </summary>
        internal static string ERROR_PerfilNazan_EliminarPropioUsuario {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EliminarPropioUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede eliminar el SuperUsuario..
        /// </summary>
        internal static string ERROR_PerfilNazan_EliminarSuperUsuario {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_EliminarSuperUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre para el perfil ya fue utilizado.
        /// </summary>
        internal static string ERROR_PerfilNazan_NombreExistente {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_NombreExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pefil incorrecto.
        /// </summary>
        internal static string ERROR_PerfilNazan_PefilIdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_PerfilNazan_PefilIdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Incorrecto.
        /// </summary>
        internal static string ERROR_UsuarioNazan_IdIncorrecto {
            get {
                return ResourceManager.GetString("ERROR_UsuarioNazan_IdIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un usuario registrado con este login.
        /// </summary>
        internal static string ERROR_UsuarioNazan_LoginExistente {
            get {
                return ResourceManager.GetString("ERROR_UsuarioNazan_LoginExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje actualizado correctamente.
        /// </summary>
        internal static string INFO_MensajesInstitucionales_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MensajesInstitucionales_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje creado correctamente.
        /// </summary>
        internal static string INFO_MensajesInstitucionales_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MensajesInstitucionales_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje eliminado correctamente.
        /// </summary>
        internal static string INFO_MensajesInstitucionales_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_MensajesInstitucionales_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil actualizado correctamente, los usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_PerfilNazan_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilNazan_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil creado correctamente.
        /// </summary>
        internal static string INFO_PerfilNazan_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilNazan_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil eliminado correctamente.
        /// </summary>
        internal static string INFO_PerfilNazan_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_PerfilNazan_EliminadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario actualizad correctamente, el usuarios deben reiniciar la sesión.
        /// </summary>
        internal static string INFO_UsuarioNazan_ActualizadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioNazan_ActualizadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario creado correctamente.
        /// </summary>
        internal static string INFO_UsuarioNazan_CreadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioNazan_CreadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario eliminado correctamente.
        /// </summary>
        internal static string INFO_UsuarioNazan_EliminadoCorrectamente {
            get {
                return ResourceManager.GetString("INFO_UsuarioNazan_EliminadoCorrectamente", resourceCulture);
            }
        }
    }
}
